name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODJjZmRiODQtYWNlNC00NTkzLTlhOGUtZTY4ZjkzNmRkMDk1IiwidGVuYW50X2lkIjoiNmJlMWVmOTRhNDVlODVhYjJlNWE1Y2QyMGRiNmVmMGU1NDc3NDI2ZjMyMTkxODBlMDFlODA5MDEyYmY1NzQ4YSIsImludGVybmFsX3NlY3JldCI6IjYxNDlmMmI1LTE2MDAtNDZkZC1iMGU4LTU4NDhhNTI0OTFkZiJ9.-jV5aojDLUD6lxNW0vVza1QKvTgOYOyL8jf8lxIEmPA"

JWT_SECRET="Rakesh@123"